import 'bootstrap/dist/css/bootstrap.min.css'
import Image from "next/image";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Container, Nav, Navbar } from "reactstrap";
import logo from "../../public/images/logo.png"
import Link from 'next/link';
import { ReactNode } from 'react';
import favicon from './favicon.ico'

const poppins = Poppins({ subsets: ["latin"], weight: ['300', '400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: "Fake Store",
  description: "Generated by create next app",
  icons: {
    icon: './favicon.ico',
  }
}

interface RootLayoutProps{
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return(
    <html lang="pt-br">
      <body className={poppins.className}>
        <div className="d-flex flex-column justify-content-between align-items-center" style={{minHeight: "100vh"}}>
          <header className='w-100'>
            <Navbar container="md">
              <Link href="/" className="navbar-brand">
                <Image
                  src={logo}
                  alt="Fake Store"
                  height={128}
                  width={267}
                  style={{width: "120px", height: "auto"}}
                  priority
                />
              </Link>
              <Nav className="flex-row gap-2 gap-md-4" navbar>
                <Link href="/" className="nav-link">
                    Home
                </Link>
                <Link href="/products" className="nav-link">
                    Todos os Produtos
                </Link>
              </Nav>
            </Navbar>
          </header>
          {children}
          <footer>
            <Container>
              <p>Desenvolvido por <a href="https://github.com/Reenas97" target='_blank'>Renata Sanchez</a> com Next.js 14.1</p>
            </Container>
          </footer>
        </div>
      </body>
    </html>
  )
}
